### ISSUE TITLE
Remove dark theme customisation?

### ISSUE THREAD

**Issue by hadley** [yihui/hugo-prose#1]
I was surprised by the default display of the site:

<img width="999" alt="Screenshot 2020-11-09 at 3 42 56 PM" src="https://user-images.githubusercontent.com/4196/98599830-3db12d00-22a2-11eb-98f9-313d061b8fb6.png">

<img width="999" alt="Screenshot 2020-11-09 at 3 43 42 PM" src="https://user-images.githubusercontent.com/4196/98599912-5c172880-22a2-11eb-9251-30319b38e864.png">

But I think this is because you have:

```css
/* dark theme */
@media (prefers-color-scheme: dark) {
  body {
    background-color: darkslategray;
    filter: invert(1);
  }
  img { filter: invert(1); }
  .article-list { box-shadow: 0 0 8px #333; }
}
```

I think the site is much more aesthetically pleasing if you don't invert all the colours.
