### ISSUE TITLE
Allow setting levels for TOC globally

### ISSUE THREAD

**Issue by apreshill** [yihui/hugo-prose#35]
One of the best features of the new Hugo Goldmark renderer is the ability to set the TOC start and end levels for your site:

https://gohugo.io/getting-started/configuration-markup/#table-of-contents

```
markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
```

I think because the Hugo variable `{{ .TableOfContents }}` isn't being used, this setting doesn't change how the TOC is displayed in the theme.
