### ISSUE TITLE
1280宽度，光标悬浮于脚注编号，脚注还是会移动过去

### ISSUE THREAD

**Issue by CyrusYip** [yihui/hugo-prose#50]
![Screenshot_20240326_113221](https://github.com/yihui/hugo-prose/assets/60951091/08153a26-7f73-4d07-831a-fc3e8793e030)

用户已经看到脚注了，没必要移动脚注，而且脚注长达超出屏幕了。

把这段css的宽度改为 1281px 可以避免这个问题。

```css
@media (min-width: 1280px) {
  .note-ref:hover + .side {
    display: inline-block;
    background-color: #f8f8f8;
    position: absolute;
    margin-left: 1em;
    padding: .5em;
    box-sizing: content-box;
  }
}
```
